
server:
  port: 8080
spring:
  application:
    name: database-server
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
        highlight_sql: true