
services:
  postgres:
    image: postgres
    container_name: video_stream_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/data/postgresql

  rtmp:
    image: rtmpsurf/rtmp
    ports:
      - "1935:1935"
      - "8090:8090"
    environment:
      HTTP_PORT: 8090
      RTMP_PORT: 1935

  keycloak:
    image: quay.io/keycloak/keycloak
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8070
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info
    ports:
      - "8070:8070"
      - "7443:7443"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8070/health/ready" ]
      interval: 15s
      timeout: 2s
      retries: 15
    command: [ "start-dev", "--http-port", "8070", "--https-port", "7443" ]
    networks:
      - local_network

  database-server:
    build:
      context: database-server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - keycloak
    environment:
      SPRING_DATASOURCE-URL: jdbc:postgresql://postgres:5432/postgres

  backend-server:
    build:
      context: backend-server
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - postgres
      - keycloak
      - database-server
    environment:
      SPRING_DATASOURCE-URL: jdbc:postgresql://postgres:5432/postgres

networks:
  local_network:
    driver: bridge