### Message Requests

###
POST /messages/new-message?message=Hello, this is a new message
Host: localhost:8888

### Identity Requests

###
GET /identities
Host: localhost:8888
Authorization: Basic admin@gmail.com admin

###
GET /identities/sse
Host: localhost:8888
Authorization: Basic admin@gmail.com admin

###
GET /identities/stream
Host: localhost:8888
Authorization: Basic admin@gmail.com admin

###
GET /identities/async
Host: localhost:8888
Authorization: Basic admin@gmail.com admin

###
GET /identities/by-id?identityId=3
Host: localhost:8888
Authorization: Basic streamer@gmail.com streamer

###
GET /identities/by-id/async?identityId=2
Host: localhost:8888
Authorization: Basic user@gmail.com user

###
POST /identities/create
Host: localhost:8888
Content-Type: application/json

{
    "nickname": "burgvv",
    "password": "cg3audio",
    "email": "burgvv@gmail.com"
}

###
POST /identities/async/create
Host: localhost:8888
Content-Type: application/json

{
    "nickname": "aston",
    "password": "martin",
    "email": "aston@gmail.com"
}

###
PUT /identities/update?identityId=5
Host: localhost:8888
Authorization: Basic burgvv@gmail.com cg3audio
Content-Type: application/json

{
    "nickname": "burgasvv",
    "email": "burgasvv@gmail.com"
}

###
PUT /identities/async/update?identityId=5
Host: localhost:8888
Authorization: Basic aston@gmail.com martin
Content-Type: application/json

{
    "nickname": "aston EDITED",
    "password": "martin EDITED"
}

### Category Reqiests

###
GET /categories
Host: localhost:8888

###
GET /categories/sse
Host: localhost:8888

###
GET /categories/stream
Host: localhost:8888

###
GET /categories/async
Host: localhost:8888

###
GET /categories/by-id?categoryId=5
Host: localhost:8888

###
GET /categories/async/by-id?categoryId=1
Host: localhost:8888

###
POST /categories/create
Host: localhost:8888
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{
    "name": "New Description",
    "description": "New Description for Category"
}

###
POST /categories/update
Host: localhost:8888
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{
    "id": 8,
    "name": "New Description EDITED",
    "description": "New Description for Category EDITED"
}

### Streamer Requests

###
GET /streamers
Host: localhost:8888

###
GET /streamers/sse
Host: localhost:8888

###
GET /streamers/stream
Host: localhost:8888

###
GET /streamers/async
Host: localhost:8888

###
GET /streamers/by-id?streamerId=3
Host: localhost:8888

###
GET /streamers/async/by-id?streamerId=1
Host: localhost:8888

###
POST /streamers/create?identityId=2
Host: localhost:8888
Authorization: Basic user@gmail.com user
Content-Type: application/json

{
    "firstname": "Иванов",
    "lastname": "Родион",
    "patronymic": "Сергеевич",
    "about": "Информация о стримере user"
}

###
POST /streamers/update?streamerId=3
Host: localhost:8888
Authorization: Basic user@gmail.com user
Content-Type: application/json

{
    "id": 3,
    "firstname": "Иванов EDITED",
    "lastname": "Родион EDITED",
    "patronymic": "Сергеевич EDITED"
}

###
POST /streamers/add-categories?streamerId=1
Host: localhost:8888
Authorization: Basic streamer@gmail.com streamer
Content-Type: application/json

{
    "id": 1,
    "categoryIds": [4, 5, 6]
}

### Stream requests

###
GET /streams/all/by-streamer?streamerId=1
Host: localhost:8888
Authorization: Basic streamer@gmail.com streamer

###
GET /streams/by-id?streamId=1
Host: localhost:8888

###
POST /streams/start?streamerId=1
Host: localhost:8888
Authorization: Basic streamer@gmail.com streamer
Content-Type: application/json

{
    "name": "New stream",
    "categoryId": 2,
    "secured": true
}

###
POST /streams/update?streamerId=1
Host: localhost:8888
Authorization: Basic streamer@gmail.com streamer
Content-Type: application/json

{
    "id": 1,
    "name": "New Stream EDITED",
    "categoryId": 4
}

###
POST /streams/stop?streamerId=1
Host: localhost:8888
Authorization: Basic streamer@gmail.com streamer
Content-Type: application/json

{
    "id": 1,
    "live": false
}

### Invitations requests

###
GET /invitations/all/by-sender?senderId=1
Host: localhost:8888
Authorization: Basic streamer@gmail.com streamer

###
GET /invitations/all/by-receiver?receiverId=1
Host: localhost:8888
Authorization: Basic streamer@gmail.com streamer

###
POST /invitations/send?senderId=1
Host: localhost:8888
Authorization: Basic streamer@gmail.com streamer
Content-Type: application/json

{
    "streamId": 1,
    "receiverId": 2
}

###
PUT /invitations/answer?invitedId=2&streamKey=9820ac8c-c78b-45b5-b278-7481c57f1aa8
Host: localhost:8888
Authorization: Basic streamerSecond@gmail.com streamerSecond
Content-Type: application/json

{
    "id": 1,
    "streamId": 1,
    "accept": true,
    "decline": false
}

### Follows Requests

###
GET /follows/by-streamer?streamerId=1
Host: localhost:8888
Authorization: Basic streamer@gmail.com streamer

###
GET /follows/by-streamer/sse?streamerId=1
Host: localhost:8888
Authorization: Basic streamer@gmail.com streamer

###
GET /follows/by-streamer/stream?streamerId=1
Host: localhost:8888
Authorization: Basic streamer@gmail.com streamer

###
GET /follows/by-streamer/secured?streamerId=1
Host: localhost:8888
Authorization: Basic streamer@gmail.com streamer

###
GET /follows/by-streamer/sse/secured?streamerId=1
Host: localhost:8888
Authorization: Basic streamer@gmail.com streamer

###
GET /follows/by-streamer/stream/secured?streamerId=1
Host: localhost:8888
Authorization: Basic streamer@gmail.com streamer

###
GET /follows/by-follower?followerId=2
Host: localhost:8888
Authorization: Basic user@gmail.com user

###
GET /follows/by-follower/sse?followerId=2
Host: localhost:8888
Authorization: Basic user@gmail.com user

###
GET /follows/by-follower/stream?followerId=2
Host: localhost:8888
Authorization: Basic user@gmail.com user

###
GET /follows/by-follower/secured?followerId=2
Host: localhost:8888
Authorization: Basic user@gmail.com user

###
GET /follows/by-follower/sse/secured?followerId=2
Host: localhost:8888
Authorization: Basic user@gmail.com user

###
GET /follows/by-follower/stream/secured?followerId=2
Host: localhost:8888
Authorization: Basic user@gmail.com user

###
POST /follows/follow?streamerId=2&followerId=1
Host: localhost:8888
Authorization: Basic admin@gmail.com admin

###
DELETE /follows/unfollow?streamerId=2&followerId=1
Host: localhost:8888
Authorization: Basic admin@gmail.com admin

### Subscribtion Requests

###
GET /subscriptions/by-streamer?streamerId=1
Host: localhost:8888
Authorization: Basic streamer@gmail.com streamer

###
GET /subscriptions/by-streamer/sse?streamerId=1
Host: localhost:8888
Authorization: Basic streamer@gmail.com streamer

###
GET /subscriptions/by-streamer/stream?streamerId=1
Host: localhost:8888
Authorization: Basic streamer@gmail.com streamer

###
GET /subscriptions/by-subscriber?subscriberId=2
Host: localhost:8888
Authorization: Basic user@gmail.com user

###
GET /subscriptions/by-subscriber/sse?subscriberId=2
Host: localhost:8888
Authorization: Basic user@gmail.com user

###
GET /subscriptions/by-subscriber/stream?subscriberId=2
Host: localhost:8888
Authorization: Basic user@gmail.com user

###
GET /subscriptions/by-streamer/secured?streamerId=1
Host: localhost:8888
Authorization: Basic streamer@gmail.com streamer

###
GET /subscriptions/by-streamer/sse/secured?streamerId=1
Host: localhost:8888
Authorization: Basic streamer@gmail.com streamer

###
GET /subscriptions/by-streamer/stream/secured?streamerId=1
Host: localhost:8888
Authorization: Basic streamer@gmail.com streamer

###
GET /subscriptions/by-subscriber/secured?subscriberId=2
Host: localhost:8888
Authorization: Basic user@gmail.com user

###
GET /subscriptions/by-subscriber/sse/secured?subscriberId=2
Host: localhost:8888
Authorization: Basic user@gmail.com user

###
GET /subscriptions/by-subscriber/stream/secured?subscriberId=2
Host: localhost:8888
Authorization: Basic user@gmail.com user

###
POST /subscriptions/subscribe?streamerId=1&subscriberId=1
Host: localhost:8888
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{
    "tariffId": 2
}

###
DELETE /subscriptions/unsubscribe?streamerId=1&subscriberId=1
Host: localhost:8888
Authorization: Basic admin@gmail.com admin
