
### Identity-Server Requests

###
GET /authentication/token
Host: localhost:8888

###
GET /identities
Host: localhost:8888
Authorization: Basic admin@gmail.com admin

###
GET /identities/by-id?identityId=3
Host: localhost:8888
Authorization: Basic streamer@gmail.com streamer

###
POST /identities/create
Host: localhost:8888
Content-Type: application/json

{
  "nickname": "burgvv",
  "password": "cg3audio",
  "email": "burgvv@gmail.com",
  "authorityId": 2
}

###
PUT /identities/update?identityId=4
Host: localhost:8888
Authorization: Basic burgvv@gmail.com cg3audio
Content-Type: application/json

{
  "nickname": "burgasvv",
  "email": "burgasvv@gmail.com"
}

### Video-Service Reqiests

###
GET /categories
Host: localhost:8888

###
GET /categories/by-id?categoryId=5
Host: localhost:8888

###
POST /categories/create
Host: localhost:8888
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{
  "name": "New Description",
  "description": "New Description for Category"
}

###
POST /categories/update
Host: localhost:8888
Authorization: Basic admin@gmail.com admin
Content-Type: application/json

{
  "id": 8,
  "name": "New Description EDITED",
  "description": "New Description for Category EDITED"
}

### Stream-Service Requests

###
GET /streamers
Host: localhost:8888

###
POST /streamers/create?identityId=2
Host: localhost:8888
Authorization: Basic user@gmail.com user
Content-Type: application/json

{
  "firstname": "Иванов",
  "lastname": "Родион",
  "patronymic": "Сергеевич",
  "about": "Информация о стримере",
  "identityId": 2
}

###
POST /streamers/update?streamerId=2
Host: localhost:8888
Authorization: Basic user@gmail.com user
Content-Type: application/json

{
  "id": 2,
  "firstname": "Иванов EDITED",
  "lastname": "Родион EDITED",
  "patronymic": "Сергеевич EDITED"
}