
create table if not exists authority (
    id bigint generated by default as identity unique not null ,
    name varchar not null unique
);

create table if not exists identity (
    id bigint generated by default as identity unique not null ,
    nickname varchar not null unique ,
    password varchar not null ,
    email varchar not null unique ,
    enabled boolean not null ,
    authority_id bigint references authority(id) on delete set null on update cascade
);

create table if not exists streamer (
    id bigint generated by default as identity unique not null ,
    firstname varchar not null ,
    lastname varchar not null ,
    patronymic varchar not null ,
    about text not null ,
    identity_id bigint references identity(id) on delete cascade on update cascade
);

create table if not exists category (
    id bigint generated by default as identity unique not null ,
    name varchar not null unique ,
    description text not null
);

create table if not exists video (
    id bigint generated by default as identity unique not null ,
    category_id bigint references category(id) on delete set null on update cascade ,
    streamer_id bigint references streamer(id) on delete cascade on update cascade ,
    name varchar not null ,
    description text not null ,
    content_type varchar not null ,
    size bigint not null ,
    format varchar not null ,
    data bytea not null
);



-- POPULATIONS



insert into authority(name) values ('ROLE_ADMIN');
insert into authority(name) values ('ROLE_USER');
insert into authority(name) values ('ROLE_STREAMER');

insert into identity(nickname, password, email, enabled, authority_id)
values ('admin','$2a$10$hjGQw1hXYTnoLPYAmoaRmuaewrE7l6AKvGF2tvavTQafhBZslvknm','admin@gmail.com',true,1);
insert into identity(nickname, password, email, enabled, authority_id)
values ('user','$2a$10$1q729f8LLJKDqdpU.awktet06vA/Ea8eoAd2a5p9sUwVkvUP29Qp.','user@gmail.com',true,2);
insert into identity(nickname, password, email, enabled, authority_id)
values ('streamer','$2a$10$EL/JBpK2PaSDdBi1ELg0/e1wtfnVYgm.0yZrOXWnxPFvdanKlHnry','streamer@gmail.com',true,3);

insert into streamer(firstname, lastname, patronymic, about, identity_id)
values ('Бутелёв', 'Владимир', 'Олегович', 'Информация о стримере', 3);

insert into category(name, description) VALUES ('Общение', 'Описание категории Общение');
insert into category(name, description) VALUES ('Игры', 'Описание категории Игры');
insert into category(name, description) VALUES ('АСМР', 'Описание категории АСМР');
insert into category(name, description) VALUES ('Музыка', 'Описание категории Музыка');
insert into category(name, description) VALUES ('Бассейны', 'Описание категории Бассейны');
insert into category(name, description) VALUES ('Сон', 'Описание категории Сон');
insert into category(name, description) VALUES ('Абстракция', 'Описание категории Абстракция');